@startuml
class Client {
- Socket socket
- PrintWriter out
- BufferedReader in
- Thread listener
+ void send(Message)
}


class Server {
- {static} Server singleton
- ServerSocket serverSocket
- Thread clientSearch
+ Server getServer()
}


class Message {
+ String type
+ String contenu
+ JSONObject getJson()
+ {static} Message fromJson(String)
}

Server "1" ..> "*" Client : socketList




@enduml