@startuml
package java {
package Modele {
    class User {
     name : String
     score : int
     serveurUtilisateur : Server
     creerContenue() : Contenu
    }

    abstract class Manche {
        centenu : Contenu
        pointMax : int
        tickDepart : long
        calculerPoint(tick long)
        start()
    }

    interface Contenu {
        proprietaire : User
        lecture()
    }

    class ContenuImage {
        image : Image
    }

    class ContenuVideo {
        video : Video
    }

    abstract class Partie {
        joueurs : ArrayList<User>
        ListeManches : ArrayList<Manche
        nbManches : int
        ajouterJoueur(j :User)
        supprimerJoueur(j :User))
        creerManches()
        start()
    }
}

package communication{
    package serveur {
        class Client {
        - Socket socket
        - PrintWriter out
        - BufferedReader in
        - Thread listener
        + void send(Message)
        }


        class Server {
        - {static} Server singleton
        - ServerSocket serverSocket
        - Thread clientSearch
        + Server getServer()
        }
        Server "1" ..> "*" Client : socketList
}
class Message {
+ String type
+ String contenu
+ JSONObject getJson()
+ {static} Message fromJson(String)
    }

    package client {
        class Client
    }
}
}
package kotlin{
    package vue {}
}
ContenuImage ..|> Contenu
ContenuVideo ..|> Contenu
Manche --> Contenu
Partie --> User
Partie --> Manche
@enduml