@startuml

class User {
 name : String
 score : int
 serverurUtilisateur : Server
 creerContenue() : Contenu
}

abstract class Manche {
    centenu : Contenu
    pointMax : int
    tickDepart : long
    calculerPoint(tick long)
    start() : Map<User,Int>
}

interface Contenu {
    proprietaire : User
    lecture()
}

class ContenuImage {
    image : Image
}

class ContenuVideo {
    video : Video
}

abstract class Partie {
    joueurs : List<User>
    ListeManches : List<Manche>
    ajouterJoueur(j :User)
    supprimerJoueur(j :User))
    creerManches()
    start() : List<User,int>
}

class Client

class Server

ContenuImage ..|> Contenu
ContenuVideo ..|> Contenu
Manche --> Contenu
Partie --> User
Partie --> Manche
@enduml